version: '3'
services:
  web:
    build: ./
    ports:
      - "5000:5000"  
    depends_on:
      - postgres
    networks:
      - backend_default
    env_file: .env  

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  
      POSTGRES_DB: user_information
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    networks:
      - backend_default

networks:
  backend_default:
    driver: bridge

volumes:
  postgres_data:
